zuul:
  routes:
    home:
      path: /osrm/**
  removeSemicolonContent: false

proxy:
  healthCoordinates:
    start: #Berlin
      latitude: 52.517037
      longitude: 13.388860
    end: #Karlsruhe
      latitude: 49.014068
      longitude: 8.404437

spring:
  profiles:
    default: dev

endpoints:
  enabled: false
  health:
    enabled: true
