profiles:
  limitInMeters: 75000
  destinations:
      underLimit: http://localhost:50002/mapsUnderLimit
      overLimit: http://localhost:50002/mapsOverLimit
      fallback: http://localhost:50002/mapsFallback
