proxy:
  profiles:
    fallback: fallbackproxy
    limit:
      driving:
        limitInMeters: 75000
        destinations:
          underLimit: http://localhost:50001/mapsUnderLimit
          overLimit: http://localhost:50001/mapsOverLimit
          fallback: http://localhost:50001/mapsFallback
    simple:
      rail:
        destination: http://localhost:50001/mapsRail
      water:
        destination: http://localhost:50001/mapsWater
      fallbackproxy:
        destination: http://localhost:50001/mapsFallbackProxy